# Generated by Django 5.2.5 on 2025-12-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='role',
        ),
    ]
