# Generated by Django 5.2.5 on 2025-12-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_designation_employee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='designation',
        ),
    ]
